apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: debian-container
      image: debian
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      command: ["bin/sh"]
      args:
        - ["-c", "echo 'Hello from Debian container' > /pod-data/index.html"]
  volumes:
    - name: shared-data
      emptyDir: {}
  