apiVersion: v1
kind: Pod
metadata:
  name: restart-always-pod
spec:
  #restartPolicy: Always    #ki isey lagaye ya na lagaye
  containers:
    - name: app
      image: alpine
      command: ["sleep", "20"]
