apiVersion: v1
kind: Pod
metadata:
  name: restart-on-failure-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: app
      image: alpine
      #command: ["sleep", "20"] # for pod `completion` state
      command: ["sh", "-c", "sleep 20; Dummy"]  # for pod `failure/restart` state