apiVersion: v1
kind: Pod
metadata:
  name: restart-never-pod
spec:
  restartPolicy: Never  #  first letter should be capital of Never
  containers:
    - name: app
      image: alpine
      command: ["sleep", "20"] 