apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
stringData:
  USERNAME: "admin"           # Plain text value for username
  PASSWORD: "adminpassword"   # Plain text value for password
