apiVersion: v1
kind: Pod
metadata:
  name: live-start-probe-http
spec:     
  containers:
    - name: liveness-nginx
      image: k8s.gcr.io/nginx
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3 # Delay before starting the probe
        periodSeconds: 3 # How often to perform the probe
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3 # Delay before starting the probe
        periodSeconds: 3 # How often to perform the probe