apiVersion: v1
kind: Pod
metadata:
  name: live-ready-probe-http
spec:     
  containers:
    - name: liveness-nginx
      image: k8s.gcr.io/nginx
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3 # Delay before starting the probe
        periodSeconds: 3 # How often to perform the probe
      readinessProbe:
        httpGet:
          path: /
          #port: 80
          port: 90    # changing port so readiness probe will fail
        initialDelaySeconds: 3 # Delay before starting the probe
        periodSeconds: 3 # How often to perform the probe