apiVersion: v1
kind: ConfigMap
metadata:
  name: player-pro-demo
data:
  # property-like keys: values
  player_lives: "5"
  properties_file_name: "user-interface.properties"

  #file-like keys.isme har ek key ek file ki tarah behave karega e.g. base.properties will like config.php
  base.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=10
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true