# binding service account to pod reader role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: sa-pod-reader  # this is binding of service account
  namespace: development
subjects:
  - kind: ServiceAccount
    name: my-serviceaccount # jo development ka my-serviceaccount hai
    namespace: development
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io