#isme hum jab tak pod create karenge jab tak worker node par kam na pad jaye resource.Yaha resourc and node slector both
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselector-app
spec:
    containers:
      - name: nginx
        image: nginx
        command:
          - sleep
          - '3600'
        resources:
          requests:
            memory: 64Mi
            cpu: 1000m
    nodeSelector:
      disktype: ssd