apiVersion: v1
kind: Pod
metadata:
  name: configmap-vol-demo
spec:
  containers:
    - name: configmap-vol-demo
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
      - name: player-map
        mountPath: /etc/config/configMap
      - name: player-secret
        mountPath: /etc/config/secret
  volumes:
    # set volumes at POD level,then mount them into containers inside that POD
    - name: player-map
      configMap:
        name: player-pro-demo   #name of configMap you want to mount
    - name: player-secret
      secret:
        secretName: example-secret # isme secret name lene but configMap mein configMap name nahiLene

